// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXBAZPCP7EmVBBaKBEzkPjC6U60C3H-o',
    appId: '1:310566241791:web:614b27c24a5f6f8b9593ca',
    messagingSenderId: '310566241791',
    projectId: 'railease-vesit',
    authDomain: 'railease-vesit.firebaseapp.com',
    databaseURL: 'https://railease-vesit-default-rtdb.firebaseio.com',
    storageBucket: 'railease-vesit.appspot.com',
    measurementId: 'G-YS6J203SKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzaixH3tX2T2aONDR_bv9RdhbpMvGnsP8',
    appId: '1:310566241791:android:044f48a3d94f2ed09593ca',
    messagingSenderId: '310566241791',
    projectId: 'railease-vesit',
    databaseURL: 'https://railease-vesit-default-rtdb.firebaseio.com',
    storageBucket: 'railease-vesit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2iJt3pNsO3rqhpjjQUfIiTucE-HgbSrs',
    appId: '1:310566241791:ios:1c8514cd591195119593ca',
    messagingSenderId: '310566241791',
    projectId: 'railease-vesit',
    databaseURL: 'https://railease-vesit-default-rtdb.firebaseio.com',
    storageBucket: 'railease-vesit.appspot.com',
    iosBundleId: 'com.example.mineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2iJt3pNsO3rqhpjjQUfIiTucE-HgbSrs',
    appId: '1:310566241791:ios:0d845797728693b59593ca',
    messagingSenderId: '310566241791',
    projectId: 'railease-vesit',
    databaseURL: 'https://railease-vesit-default-rtdb.firebaseio.com',
    storageBucket: 'railease-vesit.appspot.com',
    iosBundleId: 'com.example.mineApp.RunnerTests',
  );
}
